/**
 * App Manifest
 * Wires the full flow: form → prompt preview → generate → output
 */

import { GeneratorFormEmbed } from './embeds/generator-form';
import { PromptPreviewEmbed } from './embeds/prompt-preview';
import { GenerateActionEmbed } from './embeds/generate-action';
import { FileOutputEmbed } from './embeds/file-output';
import { LivePreviewEmbed } from './embeds/live-preview';
import { buildPrompt, type GeneratorConfig } from './lib/prompt-compiler';
import type { CodegenProvider, GeneratedFile } from './lib/llm-provider.interface';

/**
 * Mock LLM Provider for demonstration
 * In production, this would be replaced with actual AI service integration
 */
class MockCodegenProvider implements CodegenProvider {
  async generate(prompt: string): Promise<GeneratedFile[]> {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Mock generated files based on the prompt
    return [
      {
        path: 'src/embeds/example-embed.ts',
        content: `/**
 * Example Embed
 * Generated by StackLive Code Generator
 */

import { BaseEmbed } from '../lib/base-embed';

export class ExampleEmbed extends BaseEmbed {
  protected render(): void {
    this.shadow.innerHTML = \`
      <style>
        :host {
          display: block;
          font-family: var(--sl-font-family, system-ui, -apple-system, sans-serif);
        }

        .container {
          padding: 24px;
          background: #ffffff;
          border-radius: var(--sl-radius, 8px);
          box-shadow: var(--sl-shadow, 0 2px 8px rgba(0, 0, 0, 0.1));
        }

        .title {
          font-size: 20px;
          font-weight: 600;
          color: var(--sl-color-primary, #0066cc);
        }
      </style>

      <div class="container">
        <h3 class="title">Example Embed</h3>
        <p>This is a generated example embed.</p>
      </div>
    \`;
  }
}

customElements.define('example-embed', ExampleEmbed);
`
      },
      {
        path: 'src/embeds/example-embed.manifest.ts',
        content: `/**
 * Example Embed Manifest
 */

export const manifest = {
  name: 'example-embed',
  version: '1.0.0',
  description: 'An example embed generated by StackLive',
  entry: './example-embed.ts',
  config: {
    schema: {}
  }
};
`
      }
    ];
  }
}

/**
 * Application Controller
 * Manages the entire application flow
 */
export class AppController {
  private formEmbed: GeneratorFormEmbed;
  private previewEmbed: PromptPreviewEmbed;
  private actionEmbed: GenerateActionEmbed;
  private outputEmbed: FileOutputEmbed;
  private livePreviewEmbed: LivePreviewEmbed;
  private provider: CodegenProvider;

  constructor() {
    this.formEmbed = document.querySelector('generator-form') as GeneratorFormEmbed;
    this.previewEmbed = document.querySelector('prompt-preview') as PromptPreviewEmbed;
    this.actionEmbed = document.querySelector('generate-action') as GenerateActionEmbed;
    this.outputEmbed = document.querySelector('file-output') as FileOutputEmbed;
    this.livePreviewEmbed = document.querySelector('live-preview') as LivePreviewEmbed;
    
    // Use mock provider - replace with real provider in production
    this.provider = new MockCodegenProvider();

    this.initialize();
  }

  private initialize(): void {
    // Listen to form config changes
    this.formEmbed?.addEventListener('config:change', ((e: CustomEvent) => {
      this.handleConfigChange(e.detail);
    }) as EventListener);

    // Listen to generate action
    this.actionEmbed?.addEventListener('generate:start', () => {
      this.handleGenerate();
    });
  }

  private handleConfigChange(config: GeneratorConfig): void {
    // Build and update prompt preview
    const prompt = buildPrompt(config);
    this.previewEmbed?.updatePrompt(prompt);

    // Enable generate button if config is valid
    const isValid = config.name && config.description;
    this.actionEmbed?.setEnabled(!!isValid);
  }

  private async handleGenerate(): Promise<void> {
    try {
      // Get current config
      const config = this.formEmbed?.getConfig();
      if (!config) return;

      // Build prompt
      const prompt = buildPrompt(config);

      // Set generating state
      this.actionEmbed?.setGenerating(true);
      this.outputEmbed?.clearFiles();
      this.livePreviewEmbed?.clearPreview();

      // Generate files
      const files = await this.provider.generate(prompt);

      // Update output
      this.outputEmbed?.setFiles(files);

      // Update live preview with first generated file
      if (files.length > 0) {
        this.livePreviewEmbed?.updatePreview(files[0].content);
      }

      // Reset generating state
      this.actionEmbed?.setGenerating(false);
    } catch (error) {
      console.error('Generation failed:', error);
      this.actionEmbed?.setGenerating(false);
      alert('Generation failed: ' + (error instanceof Error ? error.message : 'Unknown error'));
    }
  }

  /**
   * Set a custom codegen provider
   * Use this to integrate with real AI services
   */
  public setProvider(provider: CodegenProvider): void {
    this.provider = provider;
  }
}

// Initialize app when DOM is ready
if (typeof window !== 'undefined') {
  window.addEventListener('DOMContentLoaded', () => {
    new AppController();
  });
}
